server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: bookStore-Backend
          uri: lb://BOOKSTORE-BACKEND-SERVICE
          predicates:
            - Path=/api/**
        - id: bookStore-Ui
          uri: lb://BOOKSTORE-UI-SERVICE
          predicates:
            - Path=/bookstore/**
        - id: payment
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: transportation-app
          uri: lb://TRANSPORT-SERVICE
          predicates:
            - Path=/transport/**


